import React from 'react';
const Box = (name) => (props) => <span className="icon" aria-label={name} {...props}>{name[0]}</span>;
export const Home = Box('Home');
export const Users2 = Box('Users');
export const Truck = Box('Truck');
export const Settings = Box('Settings');
export const Printer = Box('Printer');
export const RotateCcw = Box('RotateCcw');
export const Flag = Box('Flag');
export const QrCode = Box('QrCode');
export const Plus = Box('Plus');
export const Trash2 = Box('Trash2');
export const Save = Box('Save');
export const Download = Box('Download');
export default {};
