import React from 'react';
const make = (name) => (props) => <span aria-label={name} style={{display:'inline-flex',width:18,height:18,border:'1px solid #cbd5e1',borderRadius:4,alignItems:'center',justifyContent:'center',fontSize:10,marginRight:6}}>{name[0]}</span>;
export const Printer = make('Printer');
export const RotateCcw = make('RotateCcw');
export const Flag = make('Flag');
export const QrCode = make('QrCode');
export const Plus = make('Plus');
export const Trash2 = make('Trash2');
export const Save = make('Save');
export const Download = make('Download');
export default {};